#+BEGIN_COMMENT
.. title: Sage Days 25, Mumbai, India
.. date: 2010/07/21 19:41:00
.. tags: event, math, ology, python, software
.. slug: sage-days-25-mumbai-india
#+END_COMMENT





** What is 'Sage Days'?
  Sage Days is a confluence of present and prospective SAGE Users and
  Developers. It is an opportunity to come together to share ideas,
  brainstorm and hack on Sage. Sage Days 25 is the 25th version of Sage
  Days, and is being organized in Mumbai, India. In order to cater to an
  Indian audience and scenario, this version has been tweaked
  slightly. Sage Days 25 has beginner level tutorials, in addition to
  the usual talks and sprints, to help new users get started with Sage
  and help promote the use of Sage in India.

** What is Sage?
  Sage is a free, open-source mathematics software system licensed under
  the GPL. It combines the power of numerous existing open-source
  packages into a common Python-based interface. It's mission is to
  create a "viable free open source alternative to Magma, Maple,
  Mathematica and Matlab". Sage has tools for a broad range of
  mathematical areas like Linear Algebra, Calculus, Symbolic Math,
  Plotting, Rings & Groups, Graph Theory, Number Theory and
  Cryptography. Essentially, "it can do anything from mapping a
  12-dimensional object to calculating rainfall patterns under global
  warming" - as Science Daily puts it . Eager to get started? Start
  here. Apart from being feature rich, it's usability is one of it's
  greatest strengths. Sage Notebook, a web-interface for all the math
  you'll ever want to do, is really the killer feature! As the Sage
  Marketing page says, "The SAGE GUI surely works on your computer box,
  because it just runs in Firefox!". Try it Now!

** Why should you attend?
  Sage Days 25 is being attended by the creator and lead developer of
  Sage, Prof. William Stein. It will also be attended by other
  developers of Sage. This would be a great opportunity to meet and
  interact with them! The conference will be attended by a plethora of
  enthusiastic people from all over the country who use Sage or are
  interested in doing so. The conference will also see the presence of
  many mathematicians interested in software. Who knows, you may run
  into someone you'd want to collaborate with, for your future work!
  This event will be a great learning experience, if you are even
  remotely interested in math and software for it!

** When and Where?
  - Venue: IIT-Bombay, Mumbai, India
  - Dates: August 9-12, 2010
  - Tentative Schedule
  - Register Here
  - Click here for more info
