#+STARTUP: indent hidestars
#+OPTIONS: H:1 tags:nil todo:nil
#+BEGIN_COMMENT
.. title: Quotes
.. slug: quotes
.. tags:
.. category:
.. link:
.. description:
.. type: text
.. nocomments: True
#+END_COMMENT

A collection of quotes. I keep coming back to them for inspiration. Or for
brighter perspectives on life.

#+HTML: <div class="quotes">
- Furious activity is no substitute for understanding. --
  /H.H. Williams -- Activity/

- A human being should be able to change a diaper, plan an invasion,
  butcher a hog, conn a ship, design a building, write a sonnet,
  balance accounts, build a wall, set a bone, comfort the dying, take
  orders, give orders, cooperate, act alone, solve equations, analyze
  a new problem, pitch manure, program a computer, cook a tasty meal,
  fight efficiently, die gallantly. Specialization is for insects.  --
  /Robert A. Heinlein -- Human Beings/

- Nothing ever becomes real till it is experienced -- even a proverb is
  no proverb to you till your life has illustrated it. -- /John Keats/

- We lie loudest when we lie to ourselves. -- /Eric Hoffer/

- The first hour of the morning is the rudder of the day. -- /Henry
  Ward Beecher/

- Programs must be written for people to read, and only incidentally
  for machines to execute. -- /Abelson & Sussman -- SICP, preface to
  the first edition/

- In everyone's life, at some time, our inner fire goes out. It is then burst
  into flame by an encounter with another human being. We should all be
  thankful for those people who rekindle the inner spirit.  -- /Albert
  Schweitzer, 1875 - 1965/

- Anyone who cannot cope with mathematics is not fully human.  At best he is a
  tolerable subhuman who has learned to wear shoes, bathe and not make messes
  in the house.  -- /Lazarus Long, Time Enough for Love/

- You probably wouldn't worry about what people think of you if you could know
  how seldom they do. -- /Olin Miller/

- If you judge people, you have no time to love them. -- /Mother Teresa/

- Feeling gratitude and not expressing it is like wrapping a present and not
  giving it. -- /William Arthur Ward/

-
   #+begin_verse
     Where the mind is without fear and the head held high;
     Where knowledge is free;
     Where the world has not been broken up into fragments by narrow domestic walls;
     Where words come out from the depth of truth;
     Where tireless striving stretches its arms towards perfection;
     Where the clear stream of reason has not lost its way into the dreary desert sand of dead habit;
     Where the mind is led forward by Thee into ever-widening thought and action;
     Into that heaven of freedom, my Father, let my country awake.
   #+end_verse
   /Rabindranath Tagore -- Let My Country Awake/

- The true Enlightenment thinker, the true rationalist, never wants to talk
  anyone into anything. No, he does not even want to convince; all the time he
  is aware that he may be wrong. Above all, he values the intellectual
  independence of others too highly to want to convince them in important
  matters. He would much rather invite contradiction, preferably in the form of
  rational and disciplined criticism. He seeks not to convince but to arouse --
  to challenge others to form free opinions. -- /Karl Popper -- On Freedom/

- Don't ask yourself what the world needs; ask yourself what makes you come
  alive. And then go and do that. Because what the world needs is people who
  have come alive. -- /Howard Thurman/

- All you need is love. But a little chocolate now and then doesn't hurt. --
  /Charles M Schultz/

- Somewhere in the world someone is training when you are not. When you race
  him, he will win. -- /Tom Fleming/

- Because when something happens, she's the person I want to tell. The
  most basic indicator of love. -- /David Levithan/

- If you are not embarrassed by the first version of your product,
  you've launched too late. -- /Reid Hoffman/

- Nothing of me is original. I am the combined effort of everyone I've ever
  known. -- /Chuck Palahniuk/

- I fell in love with the way you sleep; slowly then all at once -- /John
  Green/

- The enjoyment of one's tools is an essential ingredient of successful
  work. -- /Donald E. Knuth/

- Respect yourself enough to walk away from anything that no longer serves you,
  grows you, or makes you happy. -- /Robert Tew/

- It is not in the stars to hold our destiny but in ourselves. -- /William
  Shakespeare/

- I saw that my life was a vast glowing empty page and I could do anything I
  wanted. -- /Jack Kerouac/

- The truth is, everyone is going to hurt you. You just got to find the ones
  worth suffering for. -- /Bob Marley/

- Scientists study the world as it is; engineers create the world that has
  never been. -- /Theodore von Karman/

- If you can love someone with your whole heart, even one person, then there's
  salvation in life. Even if you can’t get together with that person. --
  /Haruki Murakami/

- The truth is rarely pure and never simple -- /Oscar Wilde/

- Memories warm you up from the inside. But they also tear you apart. --
  /Haruki Murakami/

- We are what we repeatedly do. Excellence, then, is not an act, but a
  habit. -- /Aristotle/

- Life is a tragedy when seen in close-up, but a comedy in a long-shot. --
  /Charlie Chaplin/

- Another flaw in the human character is that everyone wants to build and
  nobody wants to do maintenance. -- /Kurt Vonnegut/

- In three words I can sum up everything I've learned about life: it goes
  on. -- /Robert Frost/

- Debugging is twice as hard as writing the code in the first place. Therefore,
  if you write the code as cleverly as possible, you are, by definition, not
  smart enough to debug it. -- /Brian Kernighan/

- Lighthouses don’t go running all over an island looking for boats to save;
  they just stand there shining. -- /Anne Lamott/

- Life is an awful, ugly place to not have a best friend. -- /Sarah Dessen/

- Warning: everything saved will be lost. -- /Wii notification/

- Happiness is nothing more than good health and a bad memory.  -- /Albert
  Schweitzer/

- Silence is the language of god. All else is poor translation. -- /Rumi/

- To love at all is to be vulnerable. Love anything, and your heart will
  certainly be wrung and possibly be broken. If you want to make sure of
  keeping it intact, you must give your heart to no one, not even to an
  animal. Wrap it carefully round with hobbies and little luxuries; avoid all
  entanglements; lock it up safe in the casket or coffin of your
  selfishness. But in that casket -- safe, dark, motionless, airless -- it will
  change. It will not be broken; it will become unbreakable, impenetrable,
  irredeemable. The alternative to tragedy, or at least to the risk of tragedy,
  is damnation. The only place outside of Heaven where you can be perfectly
  safe from all the dangers and perturbations of love is Hell. -- /C. S. Lewis/

- Quality is the result of a million selfless acts of care -- not just of any
  great method that descends from the heavens. That these acts are simple
  doesn't mean that they are simplistic; and it hardly means that they are
  easy. They are nonetheless the fabric of greatness and, more so, of beauty in
  any human endeavor. To ignore them is not yet to be fully human.  -- /James
  O. Coplien, Foreword to Clean Code/

- We are all in the same boat, in a stormy sea, and we owe each other a
  terrible loyalty. -- /G.K. Chesterton/

- The road to wisdom? -- Well, it's plain and simple to express:

  #+BEGIN_VERSE
  Err
  and err
  and err again
  but less
  and less
  and less.
  #+END_VERSE

  -- /Piet Hein (Grooks)/

- My idea of dominating is that I get all of the players on my team to play
  better than if I wasn't there. -- /Ben Wiggins/

- It is a risk to love. What if it doesn't work out? Ah, but what if it does.
  -- /Peter McWilliams/

- Wherever you go, go with all your heart -- /Confucius/

- Work is never finished, only abandoned. -- /Paul Valéry/

- Satisfaction of one's curiosity is one of the greatest sources of happiness
  in life. -- /Linus Pauling/

- I wanted to change the world. But I have found that the only thing one can be
  sure of changing is oneself. -- /Aldous Huxley/

- The true voyage of discovery consists not of going to new places, but of
  having a new pair of eyes. -- /Marcel Proust (1871–1922)/

- All that is necessary for evil to triumph is for good men to do nothing. --
  /Edmund Burke/

- I think that it's extraordinarily important that we in computer science keep
  fun in computing. When it started out, it was an awful lot of fun. Of course,
  the paying customers got shafted every now and then, and after a while we
  began to take their complaints seriously. We began to feel as if we really
  were responsible for the successful, error-free perfect use of these
  machines. I don't think we are. I think we're responsible for stretching
  them, setting them off in new directions, and keeping fun in the house. I
  hope the field of computer science never loses its sense of fun. Above all, I
  hope we don't become missionaries. Don't feel as if you're Bible
  salesmen. The world has too many of those already. What you know about
  computing other people will learn. Don't feel as if the key to successful
  computing is only in your hands. What's in your hands, I think and hope, is
  intelligence: the ability to see the machine as more than when you were first
  led up to it, that you can make it more. -- /Alan J. Perlis (April 1,
  1922-February 7, 1990)/

- Forgetting is like radiation: you cannot smell it, you cannot taste it, and
  when you finally notice the damage, it is already irreversible -- /Piotr
  Wozniack/

- Computer Science is no more about computers than astronomy is about
  telescopes -- /Edsger Dijkstra/

- Do anything, but let it produce joy. -- /Walt Whitman/

- Learn to value yourself, which means: fight for your happiness -- /Ayn Rand/

- If you don't stand for something you will fall for anything -- /Malcolm X/

- Do you want to know who you are? Don't ask. Act! Action will delineate and
  define you -- /Thomas Jefferson/

- We will be held accountable for all the permitted pleasures we failed to
  enjoy. -- /Talmud Yerwshalmi/

- It's so easy to hate. It takes strength to be gentle and kind. -- /The
  Smiths/

- To be trusted is a greater compliment than being loved -- /George MacDonald/

- I am more convinced than ever. Conceptual integrity is central to product
  quality. -- /Fred Brooks/

- If the software doesn't have to work, you can always meet any other
  requirement. -- /Gerald Weinberg/

- Twenty years from now you will be more disappointed by the things that you
  didn't do than by the ones you did. So throw off the bowlines. Sail away from
  the safe harbor. Catch the trade winds in your
  sails. Explore. Dream. Discover. -- /Mark Twain/

- Be careful when you fight the monsters, lest you become one. -- /Friedrich
  Nietzsche/

- Assume nobody else has any idea what they're doing either. A lot of people
  refuse to try something because they feel they don't know enough about it or
  they assume other people must have already tried everything they could have
  thought of. Well, few people really have any idea how to do things right and
  even fewer are to try new things, so usually if you give your best shot at
  something you'll do pretty well. -- /Aaron Swartz/

- What makes this advice especially hollow and pious is that I am not dead
  yet. If it were any good, I could easily take it myself.  -- /Kurt Vonnegut,
  in a letter to his daughter Nanny/

- Go out and walk. That is the glory of life. -- /Artist Maira Kalman/

- I think it's pretty cool that there are tutorials to do things that are
  pretty near the state of the art. -- /Dan L. on tutorials in Theano for doing
  Deep Learning stuff/

- All things worth doing are frustrating. How much satisfaction do you get from
  doing something easy? -- /Joe Armstrong/ on [[https://twitter.com/joeerl/status/673428125737459712][Twitter]]

#+HTML: </div>

#+HTML: <script type="text/javascript" src="/assets/js/quotes.js"></script>
