#+BEGIN_COMMENT
.. title: erc-notifications when Emacs not in focus
.. slug: erc-notifications-when-emacs-not-in-focus
.. date: 2014-11-06 18:05:12 UTC+05:30
.. tags: emacs, hack,
.. link:
.. description:
.. type: text
#+END_COMMENT


I have been trying to get ERC working with notifications. Julien Danjou's
wonderful [[https://julien.danjou.info/blog/2012/erc-notifications][notifications]] module for ERC is great, but it is annoying to get
notifications even when Emacs is in focus.

I had looked at [[https://github.com/eqyiel/circe-notifications/blob/master/circe-notifications.el][circe-notifications]], which has the feature but uses xdotool and
xprop to do it.  I was looking for something simpler, though... and it suddenly
struck me that I have an auto-save hook in Emacs that is run when I focus out
of it.  I wondered if I could disable and enable notifications on focus, and it
worked.

In case it is useful for somebody else -

#+BEGIN_SRC emacs-lisp
  (add-to-list 'erc-modules 'notifications)
  (erc-notifications-mode)
  (add-hook 'focus-out-hook 'erc-notifications-enable)
  (add-hook 'focus-in-hook 'erc-notifications-disable)
#+END_SRC

I wonder if there are some corner cases where this doesn't work, and that's why
the author of circe-notifications chose the tools that he did.
