#+BEGIN_COMMENT
.. title: GetHub: Chrome Notifications for Github updates
.. date: 2011-03-02 00:34:00
.. tags: chrome, code, first, git, software
.. slug: gethub-chrome-notifications-for-github-updates
#+END_COMMENT



:CLOCK:
:END:

Over the last two days, I hacked up my first Chrome extension.
I've been using Chrome only for the past couple of weeks or so and
I begin to like it, though some of the extensions aren't as mature
as I would've liked.

The original idea was floated by my friend,  Madhu, and Lee helped
me quite a bit, while I was working on it.

** What does it do?

  It is a simple extension, that shows pop-ups, whenever there is
  an update in your GitHub "Wall" (yes, this is a Facebook world)
  or News Feed as they call it.

  After installation, you will need to save your ~username~ and
  ~token~ for the extension to work.

** Where to get it?

  Presently, you will need to get it from GitHub.

  I might add it to the Chrome Web Store, once I see more people
  using it.  I couldn't justify, to myself, paying the initial
  one-time verification fee that Google asks for.

  *UPDATE*: [2011-03-04 Fri] Added GetHub to the store

** Comments and Feedback

  + Feel free to write to me at ~punchagan+gethub@jeemail.com~
  + Or file issues at GitHub.


  Happy GitHubbing!
