#+BEGIN_COMMENT
.. title: Google Trends and PV Sindhu
.. slug: google-trends-and-pv-sindhu
.. date: 2016-08-20 11:27:15 UTC+05:30
.. tags: draft
.. category:
.. link:
.. description:
.. type: text
#+END_COMMENT


TL;DR

1. Am I saying India doesn't have a caste problem?

   No, Its definitely a HUGE problem!

2. Are these articles on Google Trends and Sindhu's caste useful at all?

   Just more click-baits and no useful contribution to the discussion on caste.

-----

First of all, congratulations to PV Sindhu on making it to the finals and
giving the world number one a hard fight!

This post, though, is not a celebratory one.  I read [[http://www.thenewsminute.com/article/while-pv-sindhu-fought-hard-medal-many-indians-googled-her-caste-48545][this article]] -- While PV
Sindhu fought hard for a medal, many Indians googled her caste -- by the News
Minute thanks to a [[https://twitter.com/tmkrishna/status/766844023810117632][re-tweet by TM Krishna]].  I probably wouldn't have paid much
attention to it, if not for the retweet by TMK.

Caste is a huge problem for the country, and if you still like to pretend it
isn't -- read [[http://www.firstpost.com/india/from-gujarat-to-gurugram-atrocities-on-dalits-rise-even-as-their-protests-continue-2960548.html][this]] for a start.  I'm not surprised that *some* people searched
for Sindhu's caste while she was battling it out at Rio.  But, *some* people
also searched for Badminton rules, and others for Sania Mirza!  What surprises
me is that the article doesn't try to put the data in a context at all.  Nor do
I understand the contribution this article makes to the discussion on caste.

https://c5.staticflickr.com/9/8541/28818616900_d8e2b33cb0_b.jpg

I played around a little more with these search terms and Google Trends, and
here are a few things that I thought were worth sharing.

* Indian trends

First of all, the article says "Many Indians", and gives off cumulative
month-wise numbers.  But, what does it really mean?

I don't know if anybody actually wrote about how many people actually followed
the match, but Sindhu actually managed to get a whole lot of people interested!

https://c2.staticflickr.com/9/8014/29105184025_777ac4e5d0_b.jpg

More people searched for PV Sindhu than the daily average number of searches
(not hits) for Facebook and very close to the daily number of searches for Porn
-- two of the biggest things Internet is allegedly used for.  Can you see the
red line at the bottom?  That is the number of people who actually searched for
Sindhu's caste -- a tiny blip.

Let's take a closer look.  Here's a plot of some of the other auto suggest
terms + badminton rules & courts compared to Sindhu's name.

https://c7.staticflickr.com/9/8507/28818617070_9c9fdfeb12_b.jpg

Nothing other than badminton rules (which is at about 1% of max. searches) is
even visible, clearly.

So, these other terms (wiki & caste being auto-suggested ones) are nowhere near
the actual number of searches being made for PV Sindhu's name alone.

Let's get rid of the name graph to get a closer look at the other terms.

https://c6.staticflickr.com/9/8191/29105184165_133734e300_b.jpg

- The maximum number of people searching for Sindhu's caste is at about a fifth
  of the maximum number of people searching for badminton rules.  Interpreting
  it is upto you.  But, I'm not surprised knowing how significant caste has
  been in our society.  Also, notice that searches for wiki and caste fall off
  more gradually than the searches for the rules which peak while the game is
  being played and watched.

- Unsurprisingly, a bulk of the searches appear to be coming from Andhra and
  Telangana. Notice that the other states are searching more for the rules or
  her wiki page.

https://c8.staticflickr.com/9/8169/29105184295_f3e1448d10_b.jpg

- Do you notice that the red (caste), blue (wiki) and violet (images) lines
  following a similar trend, until the last few hours?  What do you think is
  happening there? Its the shitty click baits working!  Look at the trends from
  ~8:30AM to ~12:30AM below -- the red has spread to other states as well!

https://c6.staticflickr.com/9/8049/29105184245_6e691d318d_b.jpg


If you are wondering how much effect the appearance of the caste term in
auto-suggest is having, I don't think that's much because wiki and images are
the other auto-suggest terms, with no surges in the number of searches.

* Trends from the Telugu states

We could see that the two Telugu states were more worried about the caste, than
the rest of the country.  Let's see how abnormal they are.

https://c8.staticflickr.com/9/8293/29105183935_5bc55c03b4_b.jpg

https://c3.staticflickr.com/9/8395/28483785994_89f1c999e4_b.jpg

You can definitely see the red line more prominently.  In case, of Andhra the
peak searches for caste are at about 5% of the name searches.  A statistically
significant difference from the country.

Let's zoom in at the auto-suggest terms alone.

https://c7.staticflickr.com/9/8317/28818617430_bca8ed9d1a_b.jpg

https://c4.staticflickr.com/9/8265/29105184115_a0a8e34f4b_b.jpg

Woah, Andhra is definitely quite an aberration from the rest of the country.
From about 1/5th of the maximum number of searches for rules, the maximum
number of caste searches jumps to about twice.  Telangana also is different,
but much less so.

Again, look at TN's trends to see what's been happening in the last few hours.

https://c3.staticflickr.com/9/8426/28818617290_eb4b3a2535_b.jpg

The click bait articles are succeeding and getting more people to do these
searches.  Its not because the term appears in auto-suggest because the other
auto-suggested terms don't follow this trend.

*NOTE*: The trends and screen-shots for the states are slightly more recent
than the others.

* Conclusion

Without a context, I don't really see the point of these "news" articles.  It
seems more click-bait-y than useful to me.

If you still feel *Many* Indians were searching for Sindhu's caste, while she
was fighting it out, go ahead and play with Google trends [[https://www.google.com/trends/explore?date=now%25207-d&geo=IN&q=pv%2520sindhu,pv%2520sindhu%2520caste,porn,movies][here]].  Add/remove
terms, change the time and location filters.  Some terms that could be
interesting to add to the comparison are: Kashmir, Independence day, Facebook.

Later, I looked at the search results and then found that this article wasn't
the only one like it.  I didn't bother to read the others, but I really hope at
least some of them are talking sense.  Is any of them really trying to
contribute to the discussion on caste, meaningfully?

Also, the actual search results don't seem to give useful answers to the folks
so curious about Sindhu's caste.  I hope none of these articles are trying to
help them out.

Finally, if you are using Google Trends to write an article, [[https://medium.com/@dannypage/stop-using-google-trends-a5014dd32588#.js332qw0h][Danny Page has
some really good advice]].
