#+BEGIN_COMMENT
.. title: Org based posts in Nikola
.. slug: org-based-posts-in-nikola
.. date: 04/20/2014 05:35:10 PM UTC+05:30
.. tags: blog, nikola, orgmode, emacs
.. link:
.. description:
.. type: text
.. is_page: False
#+END_COMMENT

[[http://binchen.org/][Chen Bin]] asked me to share my Nikola+Org work-flow, and share an
example post.

The org source for any post can be found by changing the URL of a post
from ~.html~ to ~.org~.

I don't have much of a work-flow, because I don't post too often, but
here is what I typically do, to make a new post.

I start off by creating a new post using

#+BEGIN_SRC sh
  $ nikola new_post
#+END_SRC

and then give the post a title and start editing the post in Emacs.

I have a simple snippet that lets me insert tags, based on existing
tags.

{{{gist(6629020)}}}

Once I'm happy with the content of a post, I run ~nikola auto~ to
build the source and serve it locally, and see if the post "looks"
reasonable, after being rendered.

Once, I'm happy with it, I commit the post and deploy it using ~nikola
deploy~.

#+INCLUDE: "../conf.py" :lines "206-216" src python

I also have a plugin, that posts captured bookmarks and quotes onto
the blog, with a single command. I should probably make the sources of
my blog open, and push it onto GitHub.

*Update [2015-05-13 Wed]*

- I use my own [[https://plugins.getnikola.com/#orgmode][plugin]] for Nikola which lets me write posts in org-mode.  There
  is a similar [[https://github.com/redguardtoo/org2nikola][plugin]] by Chen Bin, that exports posts to intermediate html,
  that is then used by Nikola.

- The source for my blog is now on [[https://github.com/punchagan/punchagan.muse-amuse.in][GitHub]]

- I also have [[https://github.com/punchagan/dot-emacs/blob/master/punchagan.org#nikola-stuff][custom elisp]] to be able to make a new post, and deploy the site
  from within Emacs.
