#+STARTUP: indent
#+BEGIN_COMMENT
.. title: PyCon India 2016 - Propose a talk
.. slug: pycon-india-2016-propose-a-talk
.. date: 2016-05-31 15:40:43 UTC+05:30
.. tags: draft, pycon, conference, talks, advice, blab, blag
.. category:
.. link:
.. description:
.. type: text
#+END_COMMENT


CFP for PyCon 2016 is [[https://in.pycon.org/cfp/2016/proposals/][open]] and you should propose a talk!

There has been a lot of discussion on trying to improve the talk quality at the
events. As my bit of contribution to this, below is a re-hash of some good
advice from the internet on why you should give a talk, and how to submit a
good proposal.

* Why?

- You [[https://vimeo.com/96692937#t=2m56s][needn't be an expert]] on a topic. If you have enough experience about
  something to help make the next person's experience with it better, you are
  good.

- Its a great way to find people who are interested in the same things as you
  are and to get to talk to them.  If you are an introvert, you should
  [[https://emptysqua.re/blog/tech-talks-are-campfires-jesses-three-reasons-you-should-speak-at-pycon/#meet-specialists][definitely be speaking]]!

- Proposing and giving a talk is about thinking about something hard enough to
  refine your thoughts, and being able to explain it to others. Its a useful
  skill to hone.

* How?

- Talks are [[http://speaking.io/plan/talks-are-entertainment/][entertainment]]. Pick a topic that you are excited about and fascinated
  by. Let it be a general topic that will have a significant number of people
  interested in it.

- What you want the attendees to be telling their friends about your talk,
  after they go back.  Make it the [[http://blog.briancurtin.com/posts/writing-a-pycon-proposal.html][objective]] of your talk.

- Submit a complete, clear and compelling proposal. Show the reviewers that you
  are willing to put in the effort to prepare for and to give a great
  talk. Here are a [[https://github.com/akaptur/pycon-proposals/tree/master/accepted][bunch of proposals]] to see and learn from.

- Submit an outline along with your talk. Show the talk can be delivered in the
  given time and will be interesting. Include an indication of how much [[https://github.com/akaptur/pycon-proposals/blob/master/accepted/important_decisions_kaptur_2014.md#outline][time]]
  you intend to spend on each part of your talk.

- Choose a good title.  The title is what catches the attention of your
  audience when they are trying to pick a talk.  Avoid buzz words.

- Get feedback. Like any writing, feedback can be helpful at all stages --
  brainstorm while choosing topics to getting critique on the full abstract.

- Convince the reviewers that you can give a [[https://emptysqua.re/blog/seven-tips-for-pycon/#note-to-the-organizers][well-rehearsed and entertaining]] --
  link to previous talks you've given, include links to any testimonials you've
  received from your audience, etc.  If you don't have a previously recorded
  talk, give a small talk to your friends or colleagues and have it recorded.

* References

- PyCon US has some [[https://us.pycon.org/2016/speaking/talks/][good advice]] on how to submit a proposal and most of it is
  generic enough for you to use for PyCon India, or any other conference.

- These posts ([[https://emptysqua.re/blog/tech-talks-are-campfires-jesses-three-reasons-you-should-speak-at-pycon/][1]] [[https://emptysqua.re/blog/seven-tips-for-pycon/][2]] and [[https://emptysqua.re/blog/tag/conference-tips/][more]]) by Jesse Davis are so so good!

- I also liked [[https://vimeo.com/96692937]["The Talk on Talks"]] by Zach Holman.
