#+BEGIN_COMMENT
.. title: Recurse Center, 2014-07-29
.. slug: recurse-center-2014-07-29
.. date: 2014-07-29 11:20:24 UTC-04:00
.. tags: C, hack, raspberry-pi, recursecenter
.. link:
.. description:
.. type: text
.. category: recursecenter-checkins
#+END_COMMENT

* Hacking: learning by breaking stuff
- Post lunch, I started pairing with Stephanie on the exercises in the [[http://www.nostarch.com/hacking2.htm][Hacking]]
  book, and that turned out to be super fun!
- We got through the chapter on exploitation, which focussed on stack
  overflows, heap overflows, overflows in function pointers, and string
  formatting exploits.  It acted as more than a gentle refresher for C, and was
  super fun!
- Running the examples on a 64bit system, added an additional amount of
  thinking required, and was good, IMO.
- I hadn't worked along with Stephanie on the material in the first two
  chapters.  So, I went back home and tried to catch up, but couldn't get all
  of it done.

* Miscellaneous
- I spent part of the morning wrapping up the install script for the raspberry
  project, and cleaning up the repository.  [[https://github.com/kbeyer/RPi-LED-SpectrumAnalyzer][It looks reasonable now]], and I
  think I'm done with it until the end of HackerSchool.
- I also tried to look for "easy" python issues that would involve me writing
  some C code, but didn't really find anything other than documentation... I
  guess, I should pick a module and look for bugs in it, instead.
- Also, while chatting with a friend, I had to explain that I don't mention the
  last names of people or link to them, for privacy reasons.  Hacker School is
  particularly careful about not divulging information about who are at Hacker
  School each batch, and I want to keep that tradition.
