#+BEGIN_COMMENT
.. title: Recurse Center, 2014-06-11
.. slug: recurse-center-2014-06-11
.. date: 2014-06-11 15:02:11 UTC-04:00
.. tags: github, haskell, idea, recursecenter
.. link:
.. description:
.. type: text
.. category: recursecenter-checkins
#+END_COMMENT

* Plan
  Continue with the Haskell tutorials, with additional reading from
  Real World Haskell.

* Actual
  - Finished exercises 4 and 5.
    - Learnt about Type classes in Haskell and how to create them and
      make data types instances of them.
    - Also came across a new algorithm of sieving called the [[http://en.wikipedia.org/wiki/Sieve_of_Sundaram][Sieve of
      Sundaram]], which was discovered by a student.  Surprisingly, I
      never heard of it before!

* Miscellaneous
  - A few of us had an interesting discussion about various places
    people grew up in and visited, and the cultures, etc.
  - Idea: implement a GitHub dashboard for organizations (say, HS
    batches) that give you different statistics, and interesting
    graphs. (Use elm?) [Update: Tom is working on HS and GitHub
    integration. So, that's perfect!]
